### ISSUE TITLE
Заказ курса, блок согласия с условиями, отступ слева

### ISSUE THREAD

**Issue by PaxExterminatus** [PaxExterminatus/SiteDev#1]
![fireshot capture 2 - _ - http___www eshko by_](https://user-images.githubusercontent.com/25742437/30162190-7d4ec25e-93dc-11e7-8e7f-c1ff079f51a0.png)
Заказ курса, блок согласия с условиями, отступ слева

**Comment by Valentin1989** [comment]
исправлено
