### ISSUE TITLE
Новый курс

### ISSUE THREAD

**Issue by Valentin1989** [PaxExterminatus/SiteDev#3]
Добавить курс "Учимся учиться" в селект

[http://www.eshko.by/uchimsya_uchitsa](http://www.eshko.by/uchimsya_uchitsa)

**Comment by PaxExterminatus** [comment]
Для этого курса нет пробного урока, поэтому в селекторе его нет. Нужно проверить есть ли он в заказе курса.

**Comment by Valentin1989** [comment]
в заказе курса его тоже нет
